{% set name = "dbt-adapters" %}
{% set version = "1.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_adapters-{{ version }}.tar.gz
  sha256: 6c219e71b4f65e764fcc7999edc1994536c0a09c265a9a0bc7eaeb22026bb038

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - dbt-common >=1.13,<2.0
    - dbt-protos >=1.0.291,<2.0
    - pytz >=2015.7
    - agate >=1.0,<2.0
    - mashumaro >=3.9,<3.15
    - protobuf >=5.0,<6.0
    - typing_extensions >=4.0,<5.0
    # for mashumaro[msgpack]
    - msgpack-python >=0.5.6

test:
  imports:
    - dbt.adapters
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/dbt-labs/dbt-adapters
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
