schema_version: 1

context:
  name: dbt-adapters
  version: 1.22.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/dbt_adapters-${{ version }}.tar.gz
  sha256: 05bb99c30bd7ca0153976595d46c59354302ab076051f004e92a841f117e71be

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - dbt-common >=1.36,<2.0
    - dbt-protos >=1.0.291,<2.0
    - pytz >=2015.7
    - agate >=1.0,<2.0
    - mashumaro >=3.9,<3.15
    - protobuf >=6.0,<7.0
    - typing_extensions >=4.0,<5.0
    # for mashumaro[msgpack]
    - msgpack-python >=0.5.6

tests:
  - python:
      imports:
        - dbt.adapters
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: The set of adapter protocols and base functionality that supports integration with dbt-core
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/dbt-labs/dbt-adapters

extra:
  recipe-maintainers:
    - conda-forge/dbt
    - thewchan
    - rxm7706
